name: Build

on:
  pull_request:
  push:
    paths-ignore:
      - '*.md'
      - 'LICENSE*'
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'
  PROJECT_NAME: 'DtkSymbolDiff'

jobs:
  build:
    name: Build DtkSymbolDiff
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        runtime:
          - win-x64
          - win-x86
          - linux-x64
          - linux-arm64
          - osx-x64
          - osx-arm64
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Publish ${{ matrix.runtime }}
      run: |
        dotnet publish \
          --configuration Release \
          --runtime ${{ matrix.runtime }} \
          --self-contained true \
          -p:PublishSingleFile=true \
          --output ./publish/${{ matrix.runtime }}
    
    - name: Create archive (Windows)
      if: startsWith(matrix.runtime, 'win')
      run: |
        cd publish/${{ matrix.runtime }}
        zip -r ../../${{ env.PROJECT_NAME }}-${{ matrix.runtime }}.zip .
    
    - name: Create archive (Unix)
      if: startsWith(matrix.runtime, 'linux') || startsWith(matrix.runtime, 'osx')
      run: |
        cd publish/${{ matrix.runtime }}
        tar -czf ../../${{ env.PROJECT_NAME }}-${{ matrix.runtime }}.tar.gz .
    
    - name: Upload platform artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}-${{ matrix.runtime }}
        path: |
          ${{ env.PROJECT_NAME }}-${{ matrix.runtime }}.zip
          ${{ env.PROJECT_NAME }}-${{ matrix.runtime }}.tar.gz

    release:
      name: Release
      if: startsWith(github.ref, 'refs/tags/')
      runs-on: ubuntu-latest
      needs: [ build ]
      permissions:
        contents: write

      steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Organize release files
        run: |
          mkdir -p release-files
          find release-artifacts -type f \( -name "*.zip" -o -name "*.tar.gz" \) -exec cp {} release-files/ \;
          ls -lh release-files/
    
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-files/*
          draft: true
          generate_release_notes: true